#!/bin/sh
# Runs once, when the postgres volume is first created.
# Standards §7 / Tech §12: migrations use their own user; the app user has no DDL rights.
set -eu

psql -v ON_ERROR_STOP=1 -U postgres <<SQL
CREATE ROLE ${DB_MIGRATOR_USER} LOGIN PASSWORD '${DB_MIGRATOR_PASSWORD}';
CREATE ROLE ${DB_APP_USER} LOGIN PASSWORD '${DB_APP_PASSWORD}';
CREATE DATABASE ${DB_NAME} OWNER ${DB_MIGRATOR_USER};
CREATE DATABASE ${DB_TEST_NAME} OWNER ${DB_MIGRATOR_USER};
SQL

for db in "${DB_NAME}" "${DB_TEST_NAME}"; do
  psql -v ON_ERROR_STOP=1 -U postgres -d "$db" <<SQL
REVOKE ALL ON DATABASE ${db} FROM PUBLIC;
GRANT CONNECT, TEMPORARY ON DATABASE ${db} TO ${DB_APP_USER};
ALTER SCHEMA public OWNER TO ${DB_MIGRATOR_USER};
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO ${DB_APP_USER};
-- Objects the migrator creates later are readable and writable by the app, nothing more.
ALTER DEFAULT PRIVILEGES FOR ROLE ${DB_MIGRATOR_USER}
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${DB_APP_USER};
ALTER DEFAULT PRIVILEGES FOR ROLE ${DB_MIGRATOR_USER}
  GRANT USAGE, SELECT ON SEQUENCES TO ${DB_APP_USER};
ALTER DEFAULT PRIVILEGES FOR ROLE ${DB_MIGRATOR_USER}
  GRANT EXECUTE ON FUNCTIONS TO ${DB_APP_USER};
-- Schemas the migrator creates later (e.g. pgboss for the queue) are usable by the app.
ALTER DEFAULT PRIVILEGES FOR ROLE ${DB_MIGRATOR_USER}
  GRANT USAGE ON SCHEMAS TO ${DB_APP_USER};
SQL
done
