import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { parseEnv } from "node:util";
import { defineConfig } from "vitest/config";

// .env is loaded into tests; real environment variables (e.g. in CI) win.
const fileEnv = existsSync(".env") ? parseEnv(readFileSync(".env", "utf8")) : {};
const env: Record<string, string> = {};
for (const [key, value] of Object.entries({ ...fileEnv, ...process.env })) {
  if (value !== undefined) env[key] = value;
}

const shared = {
  resolve: {
    tsconfigPaths: true,
    alias: {
      // Tests run outside the React server environment; `server-only` would throw there.
      "server-only": fileURLToPath(new URL("./tests/support/server-only.ts", import.meta.url)),
    },
  },
};

export default defineConfig({
  test: {
    coverage: {
      provider: "v8",
      // Tech §14.3 and the repo coverage gate: domain rules and server code, 90% minimum.
      // Measured over unit + integration together (`pnpm test:coverage`).
      include: ["src/domain/**/*.ts", "src/server/**/*.ts"],
      exclude: [
        // Tests are not production code.
        "**/*.test.ts",
        // CLI config read by drizzle-kit, never imported by the app.
        "src/server/db/drizzle.config.ts",
        // Generated by drizzle-kit and reviewed as SQL, not TypeScript.
        "src/server/db/migrations/**",
      ],
      reporter: ["text", "html", "lcov", "json-summary"],
      reportsDirectory: "coverage",
      thresholds: { statements: 90, branches: 90, functions: 90, lines: 90 },
    },
    projects: [
      {
        ...shared,
        test: {
          name: "unit",
          environment: "node",
          include: ["src/**/*.test.ts"],
          env: { ...env },
        },
      },
      {
        ...shared,
        test: {
          name: "integration",
          environment: "node",
          include: ["tests/integration/**/*.int.test.ts"],
          globalSetup: ["tests/support/integration-setup.ts"],
          // App code under test talks to the test database as the app user.
          env: {
            ...env,
            DB_URL: env.DB_TEST_URL ?? "",
            DB_MIGRATE_URL: env.DB_TEST_MIGRATE_URL ?? "",
          },
          // One database: files run one after another so resets never race.
          fileParallelism: false,
        },
      },
    ],
  },
});
